knesset_new:
  path: /knesset/fetch/booklet
  defaults: { _controller: 'Openlaw\Controller\Command\Knesset::fetchBooklet' }
  methods: [GET]

justice_new:
  path: /justice/fetch/booklet
  defaults: { _controller: 'Openlaw\Controller\Command\Justice::fetchBooklet' }
  methods: [GET]

